CREATE INDEX IF NOT EXISTS idx_images_status_created_at ON images(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_images_user_created_at ON images(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_images_guest_created_at ON images(is_guest_upload, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_images_status_guest_created_at ON images(status, is_guest_upload, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_file_objects_orientation_size ON file_objects(orientation, width, height);
CREATE INDEX IF NOT EXISTS idx_audit_tasks_status_created_at ON audit_tasks(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_tasks_image_created_at ON audit_tasks(image_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_results_created_at ON audit_results(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_results_result_created_at ON audit_results(result, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quota_usage_date_user ON quota_usage(date DESC, user_id);
CREATE INDEX IF NOT EXISTS idx_system_logs_level_created_at ON system_logs(level, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_logs_created_at ON system_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_operation_logs_created_at ON admin_operation_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_operation_logs_action_created_at ON admin_operation_logs(action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_migration_tasks_status_created_at ON migration_tasks(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_migration_tasks_source_storage_provider ON migration_tasks(source_storage_provider_id);
CREATE INDEX IF NOT EXISTS idx_migration_tasks_target_storage_provider ON migration_tasks(target_storage_provider_id);
CREATE INDEX IF NOT EXISTS idx_migration_task_items_task_status_created_at ON migration_task_items(migration_task_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_backup_tasks_status_created_at ON backup_tasks(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_backup_tasks_target_storage_provider ON backup_tasks(target_storage_provider_id);
CREATE INDEX IF NOT EXISTS idx_backup_files_storage_provider ON backup_files(storage_provider_id);
